FORMAT: 1A
HOST: http://private-77544-khoathai.apiary-mock.com

# Polls API

# My Scenario

## POST /login

+ Request (application/json)

        {"username": "john", "password": "d0e"}


+ Response 200 (application/json)

        {"token": "s3cr3t"}

## GET /

+ Response 200 (application/json; charset=utf-8)

        {"message": "hello"}

## PATCH /cars/{id}
+ Parameters
    + id: 42 (string, required)

+ Request (application/json)

        {"color": "yellow"}

+ Response 200 (application/json)

        {"id": 42, "color": "yellow"}
